services:
  site:
    image: wazen/site:latest
    container_name: wazen-site
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
